	db "MASTER BALL@"
	db "ULTRA BALL@"
	db "POlVO BRILLO@"
	db "SUPER BALL@"
	db "# BALL@"
	db "MAPA@"
	db "SKATE-BOARD@"
	db "PIEDRA LUNAR@"
	db "ANTIDOTO@"
	db "ANTIQUEMAR@"
	db "ANTIHIELO@"
	db "DESPERTAR@"
	db "ANTIPARALIZ@"
	db "RESTAU. TODO@"
	db "MAX. POCIÓN@"
	db "HIPERPOCION@"
	db "SUPERPOCION@"
	db "POCION@"
	db "CUERDA HUIDA@"
	db "REPELENTE@"
	db "ELIXIR MÁXIMO@"
	db "PIEDRA FUEGO@"
	db "PIEDRA TRUENO@"
	db "PIEDRA AGUA@"
	db "FRUTI-ROSA@"
	db "MAS PS@"
	db "PROTEINA@"
	db "HIERRO@"
	db "CARBURANTE@"
	db "PUÑO SUERTE@"
	db "CALCIO@"
	db "CARAMELORARO@"
	db "PRECISION X@"
	db "PIEDRA HOJA@"
	db "POLVO METALICO@"
	db "PEPITA@"
	db "# MUÑECO@"
	db "CURA TOTAL@"
	db "REVIVIR@"
	db "MAX. REVIVIR@"
	db "PROTECCION X@"
	db "SUPERREPELEN.@"
	db "MAX. REPELEN.@"
	db "DIRECTO@"
	db "SUPERCAÑA@"
	db "AGUA FRESCA@"
	db "GASEOSA@"
	db "LIMONADA@"
	db "ATAQUE X@"
	db "DEFENSA X@"
	db "VELOCIDAD X@"
	db "ATAQ.ESP. X@"
	db "MONEDERO@"
	db "ZAHORI@"
	db "# FLAUTA@"
	db "REPARTIR. EXP@"
	db "CAÑA VIEJA@"
	db "CAÑA BUENA@"
	db "SUPERCAÑA@"
	db "MAS PP@"
	db "MAX. PP@"
	db "ETER@"
	db "ETER. MAX@"
	db "ELIXIR@"
	db "CURA ROSA@"
	db "ESC. CORAZON@"
	db "GARRA RAPIDA@"
	db "BAYA MELOC@"
	db "ARENA FINA@"
	db "PICO AFILADO@"
	db "BAYA ZREZA@"
	db "BAYA PERASI@"
	db "BAYA SAFRE@"
	db "FLECHA VEN.@"
	db "ROCA DEL REY@"
	db "BAYA CAQUIC@"
	db "BAYA ATANIA@"
	db "MINISETA@"
	db "SETA GRANDE@"
	db "POLVO PLATA@"
	db "MONEDA AMULETO@"
	db "AMULETO@"
	db "AGUA MISTICA@"
	db "CUCH.TORCIDA@"
	db "CINT. NEGRO@"
	db "GAFAS DE SOL@"
	db "LAZO ROSA@"
	db "PUERRO@"
	db "BOLA DE HUMO@"
	db "ANTIDERRETIR.@"
	db "IMAN@"
	db "BAYA ZIUELA@"
	db "PERLA@"
	db "PERLA GRANDE@"
	db "PIEDRA ETERNA@"
	db "HECHIZO@"
	db "POMELO@"
	db "GS BALL@"
	db "SEMI. MILAGRO@"
	db "HUESO GRUESO@"
	db "CINTA FOCUS@"
	db "POLVOENERGÍA@"
	db "RAIZ ENERGÍA@"
	db "POLVO CURACION@"
	db "HIERBA REVIVIR@"
	db "PIEDRA DURA@"
	db "HUEVO SUERTE@"
	db "POLVOESTELAR@"
	db "TR. ESTRELLA@"
	db "CARBON@"
	db "ZUMO DE BAYA@"
	db "PERISCOPIO@"
	db "REV. METALICO@"
	db "COLMILLODRAG@"
	db "RESTOS@"
	db "BAYA ZANAMA@"
	db "ESCAMADRAGÓN@"
	db "PESO BALL@"
	db "NIVEL BALL@"
	db "CEBO BALL@"
	db "RAPID BALL@"
	db "BOLALUMINOSA@"
	db "AMIGO BALL@"
	db "LUNA BALL@"
	db "AMOR BALL@"
	db "PIEDRA SOLAR@"
	db "CINTALUNARES@"
	db "MEJORA@"
	db "BAYA ARANJA@"
	db "BAYA ZIDRA@"
	db "REGADERA@"
	db "COMPETI BALL@"
	db "CARTA IMAKUNI?@"
	db "CENIZA SAGRADA@"
	db "ALA PLATEADA@"
	db "ALA ARCOIRIS@"
	db "PIEDRA DIA@"
	db "CABLE LINK@"
	db "TROFEO MORO@"
	db "DISCO EXTRAÑO@"
	db "AMULETO IRIS@"
	db "ROCIO BONDAD@"
	db "BUCEO BALL@"
	db "SANA BALL@"
	db "OCASO BALL@"
	db "CARTA FLOR@"
	db "CARTA SURF@"
	db "CARTA AZUL@"
	db "CARTA RETRATO@"
	db "CARTA AMOR@"
	db "CARTA EON@"
	db "CARTA MORFOSIS@"
	db "CARTA CELESTE@"
	db "CARTA MÚSICA@"
	db "CARTA ESPEJISMO@"
	db "DEF. ESP. X@"
	db "PIEDRA HIELO@"
	db "POLVO VELOZ@"
	db "MAGMATIZADOR@"
	db "ELECTIRIZADOR@"
	db "PROTECTOR@"
	db "SALVEYO@"
	db "ESTATUA GATO@"
	db "CAJA CONCHAS@"
	db "ELECTROSFERA@"
	db "LLAMASFERA@"
	db "HIELOSFERA@"
	db "PIEDRA KANTO@"
	db "MT01@"
	db "MT02@"
	db "MT03@"
	db "MT04@"
	db "MT05@"
	db "MT06@"
	db "MT07@"
	db "MT08@"
	db "MT09@"
	db "MT10@"
	db "MT11@"
	db "MT12@"
	db "MT13@"
	db "MT14@"
	db "MT15@"
	db "MT16@"
	db "MT17@"
	db "MT18@"
	db "MT19@"
	db "MT20@"
	db "MT21@"
	db "MT22@"
	db "MT23@"
	db "MT24@"
	db "MT25@"
	db "MT26@"
	db "MT27@"
	db "MT28@"
	db "MT29@"
	db "MT30@"
	db "MT31@"
	db "MT32@"
	db "MT33@"
	db "MT34@"
	db "MT35@"
	db "MT36@"
	db "MT37@"
	db "MT38@"
	db "MT39@"
	db "MT40@"
	db "MT41@"
	db "MT42@"
	db "MT43@"
	db "MT44@"
	db "MT45@"
	db "MT46@"
	db "MT47@"
	db "MT48@"
	db "MT49@"
	db "MT50@"
	db "MO01@"
	db "MO02@"
	db "MO03@"
	db "MO04@"
	db "MO05@"
	db "MO06@"
	db "MO07@"
