	db "LIDER@" ; CISSY
	db "LIDER@" ; DANNY
	db "LIDER@" ; RUDY
	db "LIDER@" ; LUANA
	db "LIDER@" ; DRAKE
	db "OBSERVADOR <PK><MN>@" ; TRACEY
	db "OBSERVADOR <PK><MN>@" ; TRACEY2
	db "LIDER@" ; BROCK
	db "LIDER@" ; MISTY
	db "LIDER@" ; LT_SURGE
	db "LIDER@" ; ERIKA
	db "LIDER@" ; KOGA
	db "LIDER@" ; SABRINA
	db "LIDER@" ; BLAINE
	db "JEFE@" ; GIOVANNI
	db "ELITE FOUR@" ; LORELEI
	db "ELITE FOUR@" ; BRUNO
	db "ELITE FOUR@" ; AGATHA
	db "ELITE FOUR@" ; LANCE
	db "ENT. <PK><MN>@" ; RED
	db "ENT. <PK><MN>@" ; BLUE
	db "ENT. <PK><MN>@" ; GREEN
	db "ENT. <PK><MN>@" ; YELLOW
	db "ENT. <PK><MN>@" ; CAL
	db "ROCKET@" ; BUTCH
	db "ROCKET@" ; CASSIDY
	db "CASSIDY@" ; CASSIDY_BUTCH
	db "ROCKET@" ; JAMES
	db "ROCKET@" ; JESSIE
	db "JESSIE@" ; JESSIE_JAMES
	db "ENT. <PK><MN>@" ; MOM
	db "#MANIACO@" ; BILL
	db "IMAKUNI?@" ; IMAKUNI
	db "COLECCIONISTA@" ; LAWRENCE
	db "PRO. #MON@" ; PROF_OAK
	db "PROF #MON@" ; PROF_IVY
	db "ASIST. PROF@" ; PROF_AIDE
	db "ENFERMERA@" ; NURSE
	db "OFICINISTA@" ; OFFICER
	db "JOVEN@" ; YOUNGSTER
	db "COLEGIAL@" ; LASS
	db "BELLA@" ; BEAUTY
	db "CAZABICHOS@" ; BUG_CATCHER
	db "CAZABICHOS♀@" ; BUG_CATCHER_F
	db "NADADOR♂@" ; SWIMMERM
	db "NADADORA♀@" ; SWIMMERF
	db "CAMPERO@" ; CAMPER
	db "ROSA MANIACO@" ; PINK_MANIAC
	db "#MANIACO@" ; POKEMANIAC
	db "PESCADOR@" ; FISHER
	db "MONTAÑERO@" ; HIKER
	db "ATLETA@" ; ATHLETE
	db "SIGHTSEER♂@" ; SIGHTSEERM
	db "SIGHTSEER♀@" ; SIGHTSEERF
	db "WAITRESS@" ; WAITRESS
	db "ENTRE.GUAY♂@" ; COOLTRAINERM
	db "ENTRE.GUAY♀@" ; COOLTRAINERF
	db "CATMAN@" ; SCHOOLBOY
	db "ORNITÓLOGO@" ; BIRD_KEEPER
	db "ENT. <PK><MN>@" ; CROSS
	db "OTAKU@" ;OTAKU
	db "STAFF@" ;JACE
	db "STAFF@" ;KURT
	db "STAFF@" ;KAT
	db "STAFF@" ;ALICE
;	db "CABALLERO@" ; GENTLEMAN
;	db "MAESTRA@" ; TEACHER
	db "MARINERO@" ; SAILOR
;	db "SUPER NECIO@" ; SUPER_NERD
;	db "GUITARRISTA@" ; GUITARIST
;	db "MOTORISTA@" ; BIKER
;	db "COMEFUEGOS@" ; FIREBREATHER
;	db "MALABARISTA@" ; JUGGLER
	db "CINT.NEGRO@" ; BLACKBELT_T
;	db "MENTALISTA@" ; PSYCHIC_T
;	db "CAMPISTA@" ; PICNICKER
;	db "SABIO@" ; SAGE
;	db "MEDIUM@" ; MEDIUM
;	db "POKEFAN♂@" ; POKEFANM
;	db "POKEFAN♀@" ; POKEFANF
	db "SUBMARINISTA@" ;DIVERMALE
	db "SUBMARINISTA@" ;DIVERFEMALE
	db "INGENIERO@" ;ENGINEER
	db "CAPITAN@" ;RAYMOND
	db "PIRATA@" ;CROOK
	db "PIRATA@" ;SCUZ
